export const initialState = {
  providers: [
    {
      name: 'Kanchan Sharma',
      providerUserType: 'therapist',
      isInHouse: true,
      newClients: false,
      id: 101,
      image: 'https://randomuser.me/api/portraits/women/1.jpg',
      clinicDetails: { id: 1, name: 'Bandra Clinic' },
      availabilities: {
        '2025-05-23': {
          onlineSlots: ['08:00', '09:00'],
          offlineSlots: ['11:00'],
          bothSlots: ['12:00'],
          onlineBookedSlots: ['09:30'],
          offlineBookedSlots: [],
          blockedSlots: [{ slot: '12:30', reason: 'Break' }],
        },
        '2025-05-24': {
          onlineSlots: ['10:00'],
          offlineSlots: ['11:30'],
          bothSlots: [],
          onlineBookedSlots: [],
          offlineBookedSlots: [],
          blockedSlots: [],
        },
        '2025-05-26': {
          onlineSlots: ['08:00', '09:15'],
          offlineSlots: ['10:30'],
          bothSlots: [],
          onlineBookedSlots: [],
          offlineBookedSlots: ['10:45'],
          blockedSlots: [],
        },
        '2025-05-28': {
          onlineSlots: ['09:00'],
          offlineSlots: [],
          bothSlots: ['10:00'],
          onlineBookedSlots: [],
          offlineBookedSlots: [],
          blockedSlots: [],
        },
        '2025-05-30': {
          onlineSlots: ['08:00', '09:00'],
          offlineSlots: ['10:00'],
          bothSlots: ['11:00'],
          onlineBookedSlots: ['08:30'],
          offlineBookedSlots: [],
          blockedSlots: [],
        },
      },
    },
    {
      name: 'Anjana Thattil',
      providerUserType: 'psychiatrist',
      isInHouse: false,
      newClients: true,
      id: 102,
      image: 'https://randomuser.me/api/portraits/women/2.jpg',
      clinicDetails: { id: 2, name: 'Andheri Clinic' },
      availabilities: {
        '2025-05-23': {
          onlineSlots: ['08:00', '10:15'],
          offlineSlots: [],
          bothSlots: ['12:00'],
          onlineBookedSlots: ['10:00'],
          offlineBookedSlots: [],
          blockedSlots: [{ slot: '12:15', reason: 'Break' }],
        },
        '2025-05-25': {
          onlineSlots: ['09:00', '10:15'],
          offlineSlots: ['11:00'],
          bothSlots: ['12:30'],
          onlineBookedSlots: [],
          offlineBookedSlots: [],
          blockedSlots: [],
        },
        '2025-05-27': {
          onlineSlots: ['08:00'],
          offlineSlots: ['09:45'],
          bothSlots: [],
          onlineBookedSlots: [],
          offlineBookedSlots: [],
          blockedSlots: [],
        },
        '2025-05-29': {
          onlineSlots: ['08:00', '09:15'],
          offlineSlots: [],
          bothSlots: [],
          onlineBookedSlots: ['08:45'],
          offlineBookedSlots: [],
          blockedSlots: [],
        },
      },
    },
    {
      name: 'Hijal Banerjee',
      providerUserType: 'counselor',
      isInHouse: true,
      newClients: true,
      id: 103,
      image: 'https://randomuser.me/api/portraits/men/3.jpg',
      clinicDetails: { id: 3, name: 'Juhu Clinic' },
      availabilities: {
        '2025-05-24': {
          onlineSlots: ['08:00', '09:00', '10:00'],
          offlineSlots: ['11:00'],
          bothSlots: ['12:00'],
          onlineBookedSlots: ['09:30'],
          offlineBookedSlots: [],
          blockedSlots: [],
        },
        '2025-05-25': {
          onlineSlots: ['08:30'],
          offlineSlots: ['10:00'],
          bothSlots: [],
          onlineBookedSlots: [],
          offlineBookedSlots: [],
          blockedSlots: [],
        },
        '2025-05-27': {
          onlineSlots: ['08:00', '09:15'],
          offlineSlots: ['10:00'],
          bothSlots: [],
          onlineBookedSlots: [],
          offlineBookedSlots: [],
          blockedSlots: [{ slot: '10:30', reason: 'Meeting' }],
        },
        '2025-05-28': {
          onlineSlots: ['09:00', '10:00'],
          offlineSlots: ['11:30'],
          bothSlots: [],
          onlineBookedSlots: [],
          offlineBookedSlots: [],
          blockedSlots: [],
        },
        '2025-05-30': {
          onlineSlots: ['08:00', '10:15'],
          offlineSlots: ['11:00'],
          bothSlots: ['12:00'],
          onlineBookedSlots: [],
          offlineBookedSlots: ['11:15'],
          blockedSlots: [],
        },
      },
    },
  ],
  service: 'all',
  type: 'all',
  center: 0,
  onlyAvailable: false,
  newClientsOnly: false,
  searchText: '',
  activeDate: '',
  view: 'tile',
};
